# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            harvest.client:
                base_uri: 'https://api.harvestapp.com'
                headers:
                    Harvest-Account-ID: '%env(HARVEST_ACCOUNT_ID)%'
                    Authorization: 'Bearer %env(HARVEST_API_TOKEN)%'
                    User-Agent: '%app.harvest.useragent%'

                #TODO: Handle certs correctly
                verify_peer: false
            harvest.user.oauth:
                base_uri: 'https://id.getharvest.com'
                headers:
                    User-Agent: '%app.harvest.useragent%'

                #TODO: Handle certs correctly
                verify_peer: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
